services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env # передаю ".env" но не для передачи секретов в этот файл, а для передачи секретов в "settings.py"; почему не нужно передавать секреты для "compose.yml"?
    volumes:
      - ./WebAppBE:/WebAppBE
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

# как начать сохранять сведения в базу? и загружать их в образ postgres при деплое?