"""
Django settings for WebAppBE project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os # почитать, что за пакет os? # записать импорты!
from os import environ # импортировал и os его environ--чтобы каждый раз не писать os.environ.get('...'), а лишь environ.get('...')
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ.get('DJANGO_SECRET_KEY') # или << os.environ["DJANGO_SECRET_KEY"] >>

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "0") == "1" # что это выражение означает?

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",") #'1 << environ.get('DJANGO_ALLOWED_HOSTS').split(' ') >> # сложно; почему такой синтаксис здесь и в env не python-писок?
# записать передачу секрета!

# BOT_API_SECRET = os.environ["BOT_API_SECRET"] # зачем в качестве промежуточного звена передавать секрет в settings, если можно то же самое выражение употребить сразу во view? # не смог написать импорт значения этой переменной из settings во view
BOT_TOKEN = os.environ["BOT_TOKEN"]
BOT_API_SECRET = os.environ["BOT_API_SECRET"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    "aiogram",

    'Auth.apps.AuthAppConfig',
    'Products.apps.ProductsConfig',
    'Subscriptions.apps.SubscriptionsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "Subscriptions.middleware.SubscriptionCheckMiddleware",
]

ROOT_URLCONF = 'WebAppBE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WebAppBE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = { # записать!
    'default': {
        'ENGINE': 'django.db.backends.postgresql', # заменил << 'ENGINE': 'django.db.backends.postgresql' >> --> << 'ENGINE': 'django.db.backends.postgresql_psycopg2' >> из-за той ошибки в контейнере # по Джанго, невалиднаая опция--контейнер падает; вернул как было
        "HOST": environ.get('DB_HOST'),
        "PORT": environ.get('DB_PORT'),
        "NAME": environ.get('DB_NAME'),
        "USER": environ.get('DB_USER'),
        "PASSWORD": environ.get('DB_PASS'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'Auth.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PERMISSION_CLASSES': ( # записать!
        'rest_framework.permissions.IsAuthenticated',
    )
}